before_script: npm install
script: npm run test
language: node_js
env:
  matrix:
  - PORT=80
  global:
    secure: OVB8Z9lTqK69cni2OV55KolPBGTt6gyqMbUxjiKUXdeun2MedO+2SoTXX2JX/dq+mQDuiQVFioqt7PN94W/uNrlvLB7QsTdrH0uk7smV/KddtKshvXeaE8jmsnmxgxVFJWZWXSNQI1zwXYSUnTihsEW/LTAjTbpit3HrAxTa5EwZAoUeVWEOhkDjC2VFBXoupvuBQ5wrO5sdHFjfolGWJ/rEID5l8bjHWNPSSGNPb+nK0d6uDgOjq9bGhS4rdyUg9QBUb13/+8jyEtwnoFWZTAX0hClwelblYb8FSZmvk5sJgDM0cYd/tYJcPZ9BZPtyJNrq0j6ktPiwVMoGh5Tx8mizxEwA40DmVj484pRsCqugHQPG4TGEqpoqVhZx/Y6cWqsdOcj6rYIqyG9bekizlVclHCicR7KXm+fqPFkqBblcB/uokspbr5Dl5GflMBM33qy7d3x47NistW07FGhJuWOh6/C/Y08cUjHdi4xcy0tNeNBe+npzIqBBw6SgJUnuaBAvjYQWMqqt7pwpW+EmwMxy5YRntt8wO52geH9v6cvNP4oLFTGxJFsiU8SXnp1zkyIQut1JE777Th8a47mZqGzcDVj8BSTec6GafS0nXXum7HWv6TdFyPyw/f8MkVQSq76U9nEyxbGeqJq729RwxHpj3p9gh8v5J7NqfEl82c4=
node_js:
- '10'
deploy:
  provider: firebase
  token:
    secure: Ko+BhyBITKhGmDN4gq3+OktgB7hQ9iQSHAeftznYTbbSNiwbq+FdXQF0WcZwSm2i0KdwObgo311wKSyacxVNWeeLF4Ktr7T0970/4IRQ4UVETx/qVxCsK85Wgv7q9NFzHYNd+95YQR4Df+qxK3vbv1uuIIlfZWqbQeXSibfyxexfKKgCxeSuGdwBUWmXnxRBfB7WqPEUc+yTSO7zWGDr67+JeEkNVx0AMak2K91VyUN0jEUYPg5nqVGYXD9olh0E/BE7/yZFx2jScrPegs2Exvz1aI7K4uOoyPjhZmZaqIAfyI0fid7Bp/B53JOWmK7phE2JcTjYB3Eq9nWVirqJMwqfGJqeZmQy3mnTyyAi2kssZc833zaKeGage287Fe7dihvjIFYErlchkinwWXq7GngoDn8o1VJQvpATP8k1QRhMTQPGPHDv1pbYWtpLeqdLAKMzwB46b+tgMcJfYwWoZ3e6BQRucEEmc560zr3vwRYnsQRne0TaknlBK5OIC1wOsbLB3omQ7C3OfcqSY2eTekpS9OXG9wRFnf7Z9LoQDj5dFJJ+zOZcj0jr/3577/v4h+UhIRLQ+gkUJmi+hEqLJd4qscrD39icl9yvde1S9lGEVRC/oTuY9nfAUnhGbZ6MQdiuY7txu00OWewDbi616xPqUtIcl72QRLK+mnttFcw=
  project: bityogi-3094e
